services:
  kindle-booklog:
    build: .
    environment:
      UPDATE_ALL_BOOKS: true
    volumes:
      - type: bind
        source: ./data
        target: /data
    ports:
      - '127.0.0.1:5910:5910'
