version: '3.8'

services:
  kindle-booklog:
    image: book000/kindle-booklog:v1.3.1
    volumes:
      - type: bind
        source: ./data
        target: /data
      - type: bind
        source: ./config.json
        target: /app/config.json
    env_file:
      - kindle-booklog.env
