version: '3.8'

services:
  kindle-booklog:
    build: .
    volumes:
      - data:/data
    env_file:
      - kindle-booklog.env

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/